### PR TITLE
Filtering Out Bad Words From CodeCheck ID

### PR DESCRIPTION
**Pull request by odiaz95012**
I have made changes to the Util.java file in the com/horstmann/codecheck sub-directory of the app directory. I believe I made my changes more efficient by checking each word individually as they are generated in the id for foul language. If foul language is identified in a word, then a new word is generated and replaces the old bad word in the id.

### CODE REVIEW

**Review by cayhorstmann — CHANGES_REQUESTED** [review]
It would be much simpler if `generateNewWord` could generate only good words, i.e. have the loop for checking against bad words inside. Also, give it a parameter for starting with a vowel or a consonant. Then `createPronouncableUID` simply calls `generateNewWord` four times.

**Comment by odiaz95012** [comment]
> It would be much simpler if `generateNewWord` could generate only good words, i.e. have the loop for checking against bad words inside. Also, give it a parameter for starting with a vowel or a consonant. Then `createPronouncableUID` simply calls `generateNewWord` four times.

I am a little confused about the parameter part for starting with a vowel or consonant. Isn't this already implemented in the line of code `String s = i % 2 == b ? Util.consonants : vowels;`? Other than this I believe I made all other changes in my latest commit.

**Review by cayhorstmann — COMMENTED** [review]
I see...you randomly start with a vowel or consonant. That should be fine. But the logic in `generateNewWord` is needlessly convoluted. Why the recursive call and two calls to `checkUIDForBadWords`? Just use
```
do {
  word = ...
}  while (isBadWord(word));
return word;
```
(Rename `checkUIDForBadWords` for greater clarity.)

**Comment by odiaz95012** [comment]
I believe I made the improvements you recommended. I removed the recursive call to `generateNewWord` and made it so that the word is regenerated through a do while loop if the word is a bad word. I also renamed `checkUIDForBadwords` to `isBadWord`.
Please let me know if it can be further improved.

**Comment by cayhorstmann** [comment]
Yes, that's what I wanted. But somehow you also updated a conflicting `build-instructions.md` that I am sure you didn't intend. Can you remove that from the pull request?

**Comment by odiaz95012** [comment]
> Yes, that's what I wanted. But somehow you also updated a conflicting `build-instructions.md` that I am sure you didn't intend. Can you remove that from the pull request?

I believe I was able to remove `build-instructions.md` from the pull request.

**Review by cayhorstmann — APPROVED** [review]

**Pull request merged**
