### PR TITLE
Modified readDescription() to remove relative links from problem statements

### PR DESCRIPTION
**Pull request by charlesnguyen8**
I made changes to the readDescription() method from Problem.java in app/com/horstmann/codecheck. I initially used simple string manipulation but find it to be really easy to make mistakes, so I changed to using regular expressions. I was given ideas from looking at how images are replaced with data URIs also in readDescription().

### CODE REVIEW

**Review by cayhorstmann — CHANGES_REQUESTED** [review]
I am confused about this. The pattern `[<]\\s*[aA].*[aA]\\s*[>]` matches for example `<area>`. Do you mean `<\\s*[aA]\\s+[^>]*>`? That matches `<a ...>`.  

Also, if you are already going the regex route, why not use groups? Match the entire thing with something like
```
<\\s*[aA]\\s+[^>]*[hH][rR][eE][fF]\s*=\s*['"]([^'"]+)['"][^>]*>([^<]*)</\s*[aA]\s*>
```
Then extract `.group(1)`. If it is relative, you get the link text as `group(2)`.

**Comment by charlesnguyen8** [comment]
> 



> I am confused about this. The pattern `[<]\\s*[aA].*[aA]\\s*[>]` matches for example `<area>`. Do you mean `<\\s*[aA]\\s+[^>]*>`? That matches `<a ...>`.
> 
> Also, if you are already going the regex route, why not use groups? Match the entire thing with something like
> 
> ```
> <\\s*[aA]\\s+[^>]*[hH][rR][eE][fF]\s*=\s*['"]([^'"]+)['"][^>]*>([^<]*)</\s*[aA]\s*>
> ```
> 
> Then extract `.group(1)`. If it is relative, you get the link text as `group(2)`.

I see, the pattern you suggested is a lot more accurate. One thing I want to ask is if the regex patterns should be put near IMG_PATTERN as static final? Also, I chose the regex route as I believe it will be easier to capture the pattern and make less mistakes than using simple string manipulation. However, I keep on wondering about the efficiency of this approach and want to ask for your opinion on it?

**Comment by cayhorstmann** [comment]
Sure, static final is fine. I am not worried about efficiency of the regex.

**Comment by charlesnguyen8** [comment]
For the new commit, I used your regex pattern but changed it a little bit since it did not catch nested elements like this one
`<a href = "#ebook1"><code>This Element</code></a>`
Continuing trying to solve it with only one regex pattern proved to be difficult since there are many possibilities. 
Finally, I decided to divide the regex pattern into 2 patterns, one to catch the first part `<a href="#somelink">` and another pattern to catch `</a>`. Starting points and ending points of those 2 patterns provide me with enough information to replace relative links as needed.
I tested the new code against all the wiley problems and 10 more of my own devise problem and it all worked out.

**Review by cayhorstmann — APPROVED** [review]

**Pull request merged**
